"""PDF export utilities for analysis results.

Requires: reportlab
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def export_pdf(
    results: dict[str, Any],
    filename: str | Path,
    title: str = "MechLab Analysis Report",
) -> None:
    """
    Export analysis results to PDF file.

    Args:
        results: Dictionary of result key-value pairs
        filename: Output PDF filename or path
        title: Report title

    Example:
        >>> results = {'σ1': 112.5, 'σ2': 37.5, 'unit': 'MPa'}
        >>> export_pdf(results, 'stress_report.pdf')
    """
    filepath = Path(filename)
    c = canvas.Canvas(str(filepath), pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, title)

    # Date
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 70, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    # Separator
    c.line(50, height - 80, width - 50, height - 80)

    # Results
    c.setFont("Helvetica", 11)
    y = height - 110

    for key, value in results.items():
        if y < 50:
            c.showPage()
            c.setFont("Helvetica", 11)
            y = height - 50

        if isinstance(value, float):
            line = f"{key}: {value:.6g}"
        else:
            line = f"{key}: {value}"

        c.drawString(60, y, line)
        y -= 20

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(50, 30, "Generated by MechLab - Mechanical Engineering Laboratory")

    c.showPage()
    c.save()
